### ISSUE TITLE
move khaos to a sub-package

### ISSUE THREAD

**Issue by noahdietz** [30x/khaos-monkey#5]
I was thinking we could move the functionality for random `khaos` events into a sub-package and just call it from `main.go`

something like `khaos.RandomEvent(clientset)` that picks a destructive API call at random, i.e. `KillRandomPod`, `KillRandomSvc`, etc.

Thoughts?

**Comment by jbowen93** [comment]
I like the idea of being able to select events from a sub package. It would be nice if we didn't have to always pass around the client config but it may be more trouble than it's worth to avoid that.
